#!/usr/bin/env python3
from libtrx.cli.additional_lint import run_script
from libtrx.paths import LIBTRX_REPO_DIR

run_script(root_dir=LIBTRX_REPO_DIR, ignored_patterns=["*.patch", "*.bin", "gl_core_3_3.h"])
